// inbox
export const TOGGLE_NOTIFICATIONS_WINDOW = 'TOGGLE_NOTIFICATIONS_WINDOW';
export const SET_SELECTED_NOTIFICATION = 'SET_SELECTED_NOTIFICATION';

// user
export const SET_USER = 'SET_USER';

// user-event
export const SET_EVENT_DATE_SELECTION = 'SET_EVENT_DATE_SELECTION';
export const SELECT_EVENT_DATE_SELECTION = 'SELECT_EVENT_DATE_SELECTION';

// event
export const SET_EVENT_PAGE_CURRENT_TAB = 'SET_EVENT_PAGE_CURRENT_TAB';
export const SET_EVENT_RETREIVE = 'SET_EVENT_RETREIVE';
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS';

// create event
export const SET_CREATE_EVENT_VIEW = 'SET_CREATE_EVENT_VIEW';
export const SET_TITLE = 'SET_TITLE';
export const SET_DATE_SELECTION_TYPE = 'SET_DATE_SELECTION_TYPE';
export const SET_TYPE = 'SET_TYPE';
export const SET_DATE = 'SET_DATE';
export const SET_TIME = 'SET_TIME';

