// inbox
export const TOGGLE_NOTIFICATIONS_WINDOW = 'TOGGLE_NOTIFICATIONS_WINDOW';
export const SET_SELECTED_NOTIFICATION = 'SET_SELECTED_NOTIFICATION';

// user
export const SET_USER = 'SET_USER';

export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS';